# Guard: this project requires GNU Make
ifndef MAKE_VERSION
$(error This project requires GNU Make. On macOS, install it with: brew install make)
endif

# Guard: Make functions break with spaces in paths
ifneq (1,$(words $(abspath $(lastword $(MAKEFILE_LIST)))))
$(error The project path contains spaces. Please move or rename the directory.)
endif

GIMLI_DIR := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
REF_DIR = $(GIMLI_DIR)/c/ref
REF_SOURCES = $(REF_DIR)/gimli.c
REF_HEADERS = $(REF_DIR)/gimli.h

AVX_DIR = $(GIMLI_DIR)/c/avx2
AVX_SOURCES = $(AVX_DIR)/gimliv.c
AVX_HEADERS = $(AVX_DIR)/gimliv.h

# --------------------------------------------------------------------

JAZZ_DIR = $(GIMLI_DIR)/jasmin

JAZZ_REF = $(JAZZ_DIR)/ref
JAZZ_MAIN = $(JAZZ_REF)/jazz_gimli.jazz
JAZZ_SOURCES = $(JAZZ_REF)/gimli.jazz $(JAZZ_MAIN)
JAZZ_ASM = $(JAZZ_REF)/jazz_gimli.s
JAZZ_HEADERS = $(JAZZ_REF)/jazz_gimli.h

JAZZ_AVX = $(JAZZ_DIR)/avx2
JAZZ_MAIN_AVX = $(JAZZ_AVX)/jazz_gimliv.jazz
JAZZ_SOURCES_AVX = $(JAZZ_AVX)/gimliv.jazz $(JAZZ_MAIN_AVX)
JAZZ_ASM_AVX = $(JAZZ_AVX)/jazz_gimliv.s

# --------------------------------------------------------------------

TEST_DIR = $(GIMLI_DIR)/test

# --------------------------------------------------------------------

PROOF_DIR = $(GIMLI_DIR)/proof
